{
 "title": "GOLF APP NA JA",
 "description": "Application metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Kaldis Business Flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 1, "y": 1 },
   "content": "<h1><center>Submit Policy</center></h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "content": "<h1><center>Verify Policy</center></h1>"
  },
  {
   "type": "singlestat",
   "description": "Policy Submittted",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "submit_policy{success=\"true\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Policy Submittted",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "submit_policy{success=\"false\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Policy Submittted",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "verify_policy{success=\"true\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Policy Submittted",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "verify_policy{success=\"false\"}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "submit_policy{success=\"true\"}",
     "legendFormat": "success"
    },
    {
     "expr": "submit_policy{success=\"false\"}",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "verify_policy{success=\"true\"}",
     "legendFormat": "success"
    },
    {
     "expr": "verify_policy{success=\"false\"}",
     "legendFormat": "failed"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Error rate",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"^5..$\"}[1m])) /  sum(increase(http_request_duration_ms_count[1m]))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_count[1m])) by (service, route, method, code)  * 60",
     "legendFormat": "{{service}} - {{method}} {{route}} {{code}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Median Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_ms_bucket[1m])) by (le, service, route, method))",
       "legendFormat": "{{service}} - {{method}} {{route}}"
      }
     ]
    },
    {
     "title": "95th Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[1m])) by (le, service, route, method))",
       "legendFormat": "{{service}} - {{method}} {{route}}"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_external_memory_bytes / 1024) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Business", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Checkouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(checkouts_total[1m])) by (payment_method)  * 60",
     "legendFormat": "{{payment_method}}"
    }
   ]
  }
 ]
}